site_name: Documentation
site_url: https://docs.oikolab.com
site_description: Documentation for Oikolab API
nav:
  - Overview: index.md
  - Quickstart: quickstart.md
  - Datasets & Parameters: datasets.md
  - API Reference: references.md
  - Tips & Tricks: tips-tricks.md
  - FAQ: faq.md
  - About: about.md
theme:
  name: material
  features:
    - content.code.copy
  favicon: img/favicon_600.png
  logo: img/logo-white.png
  palette:
    primary: custom
plugins:
  - table-reader
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - abbr
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  homepage: https://oikolab.com
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/oikoweather
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/oikolab
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2023 Oikolab Ltd.
